### ISSUE TITLE
Could not open input file: artisan

### ISSUE THREAD

**Issue by rosevinod** [Flynsarmy/laravel-5-todo-tutorial#2]
HI i am trying to run this but.. getting error:

Could not open input file: artisan

After download i have run:

composer install 
and 
php artisan but getting error on artisan ...

Can you help me out in this ??

**Comment by Flynsarmy** [comment]
This isn't a full laravel repo it's just reference code to make sure what you're doing is correct. Follow the tutorial on my blog and just use this code only for reference.
