### ISSUE TITLE
Tutorial links are dead..

### ISSUE THREAD

**Issue by steven7mwesigwa** [Flynsarmy/laravel-5-todo-tutorial#5]
Please **fix** the tutorial links from your `README.md `file:-
Links:-
1.  https://www.flynsarmy.com/
2.  https://www.flynsarmy.com/2015/02/creating-a-basic-todo-application-in-laravel-5-part-1

## Both links return : -
```
The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```

**Comment by Flynsarmy** [comment]
Fixed. Thanks for letting me know!
